FROM php:8.2-apache


# Set timezone (opsional; kamu juga sudah set TZ di compose)
ENV TZ=Asia/Makassar


# Install OS deps + PHP extensions umum untuk Laravel
RUN apt-get update && apt-get install -y \
git \
unzip \
zip \
libzip-dev \
libpng-dev \
libjpeg-dev \
libfreetype6-dev \
libicu-dev \
libonig-dev \
libxml2-dev \
curl \
&& docker-php-ext-configure gd --with-freetype --with-jpeg \
&& docker-php-ext-install -j$(nproc) \
pdo_mysql \
mbstring \
zip \
exif \
pcntl \
intl \
gd \
&& a2enmod rewrite headers \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*


# Composer (ambil dari image resmi)
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer


# Set Apache DocumentRoot ke /public
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' \
/etc/apache2/sites-available/000-default.conf \
/etc/apache2/apache2.conf \
/etc/apache2/conf-available/*.conf


WORKDIR /var/www/html


# Untuk dev: tidak COPY source code di sini karena di-mount dari host lewat volumes
# Tapi tetap boleh taruh default permission folder, nanti command compose juga handle.
RUN mkdir -p storage bootstrap/cache \
&& chown -R www-data:www-data /var/www \
&& chmod -R 775 /var/www


EXPOSE 80